use customer;
select * from updated_customer_data;
-- Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purschase_amount)
from updated_customer_data
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purschase_amount
from updated_customer_data
where discount_applied = 'Yes' and purschase_amount >= (select avg(purschase_amount) from
updated_customer_data);


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as high_avg_review
from updated_customer_data
group by item_purchased
order by avg(review_rating) desc
limit 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, round(avg(Purschase_amount),2) as avg_purchase
from updated_customer_data
group by shipping_type
having shipping_type in ('Express', 'Standard')
order by avg(Purschase_amount) desc;
-- express has higher avg purchase amount

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select  subscription_status, count(customer_id) as total_customers,
round(avg(purschase_amount),2) as avg_purchase,
sum(purschase_amount) as total_revenue
from updated_customer_data
group by  subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased as item,
round(sum(case when discount_applied = 'Yes' then 1 else 0 end) / count(*) * 100,2) as discount_rate
from updated_customer_data
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases = 1 then "new"
    when previous_purchases between 2 and 10 then "Returning"
    else "loyal"
    end as customer_segment
    from updated_customer_data)
    
    select customer_segment, count(*) as "Number of customers"
    from customer_type
    group by customer_segment;
    
-- Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by  category order by count(customer_id) desc) as item_rank
from updated_customer_data
group by category , item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- 09. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from updated_customer_data
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group?
with age_group as (
select sum(purschase_amount) as total_revenue,
case
	when age >=18 and age <=30 then "young adult"
    when age > 30 and age <= 60 then "adult"
    else "old"
    end as customer_age_group
    from updated_customer_data
    group by customer_age_group)
    
select * from age_group
order by total_revenue desc;

select * from updated_customer_data;
